# Make it so I can call scripts in this directory easily
export PATH="$PATH:~/repos/ai-village/application/scripts"

# Terraform
alias tf=terraform
alias tfa='terraform apply -auto-approve'
alias tfd='terraform destroy -auto-approve'